[package]
name = "day01"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc = { path = "../aoc" }
itertools = "0.10.5"

[[bin]]
path = "src/rusty-zig.rs"
name = "rusty-zig"

[[bin]]
path = "src/streaming.rs"
name = "streaming"

[[bin]]
path = "src/streaming_three.rs"
name = "streaming_three"

