[package]
name = "aoc-2020-04"
version = "0.1.0"
authors = ["Chris Burgess <9002722+cgburgess@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
